// <auto-generated />
using AtlanticCarsPortal.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtlanticCarsPortal.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AtlanticCarsPortal.Domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AverageSpeed")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("CarType")
                        .HasColumnType("int");

                    b.Property<decimal>("KMPerLiter")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("QtdTankLiter")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TankCapacity")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageSpeed = 205m,
                            CarType = 1,
                            KMPerLiter = 12m,
                            Model = "Toyota Corolla",
                            Price = 140000m,
                            QtdTankLiter = 20m,
                            TankCapacity = 50m
                        },
                        new
                        {
                            Id = 2,
                            AverageSpeed = 167m,
                            CarType = 1,
                            KMPerLiter = 12.9m,
                            Model = "Chevrolet Onix",
                            Price = 75000m,
                            QtdTankLiter = 30m,
                            TankCapacity = 54m
                        },
                        new
                        {
                            Id = 3,
                            AverageSpeed = 180m,
                            CarType = 1,
                            KMPerLiter = 12.9m,
                            Model = "Chevrolet Prisma",
                            Price = 65000m,
                            QtdTankLiter = 35m,
                            TankCapacity = 54m
                        },
                        new
                        {
                            Id = 4,
                            AverageSpeed = 177m,
                            CarType = 2,
                            KMPerLiter = 11.1m,
                            Model = "Volkswagen Gol",
                            Price = 73000m,
                            QtdTankLiter = 35m,
                            TankCapacity = 55m
                        },
                        new
                        {
                            Id = 5,
                            AverageSpeed = 185m,
                            CarType = 1,
                            KMPerLiter = 11.1m,
                            Model = "Volkswagen Voyage",
                            Price = 85000m,
                            QtdTankLiter = 35m,
                            TankCapacity = 55m
                        },
                        new
                        {
                            Id = 6,
                            AverageSpeed = 187m,
                            CarType = 1,
                            KMPerLiter = 10.1m,
                            Model = "Fiat Palio",
                            Price = 55000m,
                            QtdTankLiter = 25m,
                            TankCapacity = 48m
                        },
                        new
                        {
                            Id = 7,
                            AverageSpeed = 184m,
                            CarType = 3,
                            KMPerLiter = 10.1m,
                            Model = "Fiat Argo",
                            Price = 80000m,
                            QtdTankLiter = 15m,
                            TankCapacity = 48m
                        },
                        new
                        {
                            Id = 8,
                            AverageSpeed = 195m,
                            CarType = 1,
                            KMPerLiter = 10.1m,
                            Model = "Fiat Toro",
                            Price = 180000m,
                            QtdTankLiter = 40m,
                            TankCapacity = 60m
                        },
                        new
                        {
                            Id = 9,
                            AverageSpeed = 180m,
                            CarType = 1,
                            KMPerLiter = 9m,
                            Model = "Toyota Hilux",
                            Price = 285000m,
                            QtdTankLiter = 40m,
                            TankCapacity = 80m
                        },
                        new
                        {
                            Id = 10,
                            AverageSpeed = 180m,
                            CarType = 1,
                            KMPerLiter = 9m,
                            Model = "Toyota SW4",
                            Price = 386000m,
                            QtdTankLiter = 40m,
                            TankCapacity = 80m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
